# docker-compose up --build
# docker-compose build --no-cache
version: '3.8'
services:
  frontend.web:
    container_name: frontend
    restart: always
    build: .
    expose:
      - 3000
    ports:
      - '80:3000'
    volumes:
      - .:/app
      - /app/node_modules
